### ISSUE TITLE
Question about DDL queue and downloading in general

### ISSUE THREAD

**Issue by mightyflub** [mylar3/mylar3#515] opened 2020-10-25 21:04 UTC
I'd like to better understand how the ddl queue works. I was having a lot of problems all of a sudden getting anything to donwload. Things would be listed as snatched and never show up. I think I had something causing issues with the queue so I set everything back to skipped and started changing stuff to wanted slowly.

Now things are appearing in the ddl queue and also my nzb searches. Some are getting downloading and processed. The rest of the ddl queue is just sitting there with the status queued and the option to start (Which doesn't seem to do anything) on the right. Does the ddl queue run on an internal timer so as not to overstress getcomics? I just want to make sure I've finally got everything running properly now.

[carepackage.zip](https://github.com/mylar3/mylar3/files/5435954/carepackage.zip)
I'm using it on Linux under docker from this repo (I check for updates often and I'm on the version listed on the docker page)
https://hub.docker.com/r/hotio/mylar3

**Comment by mightyflub** [comment] 2020-10-25 21:09
Looks like as I was typing this up my ddl queue has started again and appears to be working. So I think previously I must have had something stuck that Mylar didn't like 👍

**Comment by mightyflub** [comment] 2020-10-26 09:03
And it's happening again. I have issues that were ddl downloaded and marked as complete nearly 11 hours ago that are still showing as snatched in the database and appear to have vanished into thin air. I also have nearly 100 items that have been queued in the ddl queue for about the same time with no movement
Here's a fresh care package (I restarted this morning to see if it would wake up)

[carepackage.zip](https://github.com/mylar3/mylar3/files/5437821/carepackage.zip)

**Comment by evilhero** [comment] 2020-10-26 14:53
There's multiple errors in the logs, so I'm not quite sure which ones are being caused by the other in sequence.

But here's what I did see:
- the post-processor locked up on trying to post-process the ```50.LR``` issue. ATM, this kills any subsequent post-processing and requires the restart of Mylar in order to get the queue active again.
- the search queue was getting 2 different errors:
    - one was due to a timeout trying to reach the search provider. This could be caused by traffic on there end limiting the amount of connections, or possibly even due to hammering of search requests.
    - the other was due to a parsing error on one of the search result titles, which I've been able to duplicate on my end and am working thru fixing that one now.

**Comment by mightyflub** [comment] 2020-10-26 15:52
Was it the ddl provider? I could understand if they've got code to stop us hammering the crap out of them :) My hydra server not so much :).

Thanks for looking into things for me. Much appreciated. For the moment I think I'll stop the LR titles from doing any searching.

**Comment by evilhero** [comment] 2020-10-26 15:59
Nope - it was the DDL provider, but the search queue died on the error being returned from the DDL so it never got to your nzb provider.  There are slight delays in searching against the DDL, and in downloading - so we should be fine from that aspect as everything has to go thru the queue to search. There's a soon to be released fix that will allow for items to continue searching / downloading / post-processing even after an error occurs and would normally stall the queue.

The LR fixes are in the master branch now. Depending on when your docker updates, you'll be fine to post-process LR issues (note that it only affects post-processing, searching and file-checking from within the series work as expected).

**Comment by mightyflub** [comment] 2020-10-26 16:06
That's brilliant. Thank you. I'll keep an eye out for the docker updating. (Apparently 31 minutes ago it turns out)

**Comment by barbequesauce** [comment] 2020-11-06 01:20
are we good to close this?

**Closed** 2022-03-30 19:19 UTC
Labels: enhancement
