### ISSUE TITLE
Import Datatables error.

### ISSUE THREAD

**Issue by ElementSixtySix** [mylar3/mylar3#276] opened 2020-05-02 12:05 UTC
On Import or Mass Import, popup error box: "DataTables warning: table id=impresults_table - Cannot reinitialise DataTable. For more information about this error, please see http://datatables.net/tn/3"

 - OS: Windows 7 x64
 - Branch / commit: Version: 9eefa84457f85f777c01628eb01f76b0a802984b (master)

[carepackage.zip](https://github.com/mylar3/mylar3/files/4567639/carepackage.zip)

**Comment by barbequesauce** [comment] 2020-05-06 00:44
Duplicate of #255

**Closed by barbequesauce** 2020-05-06 00:44 UTC
Labels: bug
