### ISSUE TITLE
Index out of range error when some issues don't have a year

### ISSUE THREAD

**Issue by ajw107** [mylar3/mylar3#1023] opened 2022-01-27 11:32 UTC
**Describe the bug**
On the Dev branch during the DB update I was getting an index out of range error with the [yearposition+1] index of the split_file array.  I'll add some examples as to when this happened below (I added more debug logging of variables to see what was happening).  I got round it by adding an extra guard for the size of the array to line 1170, changing:
`if highest_series_pos <= issue_number_position and all([len(split_file[0]) == 4, split_file[0].isdigit()]):`
to
`if highest_series_pos <= issue_number_position and all([len(split_file[0]) == 4, split_file[0].isdigit()]) and (yearposition+1) < len(split_file):`

But as I don;t know anything about the code, I do not know if this is appropriate.

**CarePackage**
*First Example*
```
27-Jan-2022 10:45:51 - DEBUG   :: mylar.parseit.330 : MAIN : Scanner group tag discovered: Minutemen-TurkeyDog
27-Jan-2022 10:45:51 - DEBUG   :: mylar.parseit.447 : MAIN : NEWLY SPLIT REORGD: ['Ms', 'Tree', '(Renegade Press)', '25', '(1986)']
27-Jan-2022 10:45:51 - DEBUG   :: mylar.parseit.477 : MAIN : checking date : 1986
27-Jan-2022 10:45:51 - DEBUG   :: mylar.parseit.485 : MAIN : date: 1986
27-Jan-2022 10:45:51 - DEBUG   :: mylar.parseit.839 : MAIN : datecheck: [{'date': '1986', 'position': 4, 'mod_position': 31}]
27-Jan-2022 10:45:51 - DEBUG   :: mylar.parseit.845 : MAIN : sctd: 2022
27-Jan-2022 10:45:51 - DEBUG   :: mylar.parseit.853 : MAIN : year verified as : None
27-Jan-2022 10:45:51 - DEBUG   :: mylar.parseit.861 : MAIN : year verified as: 1986
27-Jan-2022 10:45:51 - DEBUG   :: mylar.parseit.893 : MAIN : highest_series_position: 4
27-Jan-2022 10:45:51 - DEBUG   :: mylar.parseit.913 : MAIN : possible_issuenumbers: [{'number': '25', 'position': 3, 'mod_position': 27, 'validcountchk': False}]
27-Jan-2022 10:45:51 - DEBUG   :: mylar.parseit.962 : MAIN : issue number :25
27-Jan-2022 10:45:51 - DEBUG   :: mylar.parseit.991 : MAIN : issue_position: 3
27-Jan-2022 10:45:51 - DEBUG   :: mylar.parseit.1019 : MAIN : issue verified as : 25
27-Jan-2022 10:45:51 - DEBUG   :: mylar.parseit.1154 : MAIN : sf_highest_series_pos: ['Ms', 'Tree', '(Renegade Press)']
27-Jan-2022 10:45:51 - DEBUG   :: mylar.parseit.1155 : MAIN : yearposition: 4
27-Jan-2022 10:45:51 - DEBUG   :: mylar.parseit.1158 : MAIN : split_file array size: 5
27-Jan-2022 10:45:51 - ERROR   :: mylar.excepthook.315 : MAIN : Uncaught exception: Traceback (most recent call last):
  File "/app/mylar3/Mylar.py", line 449, in <module>
    main()
  File "/app/mylar3/Mylar.py", line 315, in main
    restart_method = ur.update_db()
  File "/app/mylar3/mylar/maintenance.py", line 507, in update_db
    filelist = flc.listFiles()
  File "/app/mylar3/mylar/filechecker.py", line 117, in listFiles
    runresults = self.parseit(self.dir, self.file)
  File "/app/mylar3/mylar/filechecker.py", line 1159, in parseit
    logger.fdebug('split_file[yearposition+1]: %s' % split_file[yearposition+1])
IndexError: list index out of range
```
*Second Example*
```
27-Jan-2022 10:47:35 - DEBUG   :: mylar.parseit.330 : MAIN : Scanner group tag discovered: Digital-Empire
27-Jan-2022 10:47:35 - DEBUG   :: mylar.parseit.447 : MAIN : NEWLY SPLIT REORGD: ['Zero', 'v02', '-', 'At', 'the', 'Heart', 'of', 'It', 'All', '(2014)']
27-Jan-2022 10:47:35 - DEBUG   :: mylar.parseit.703 : MAIN : volume label detected as : Volume 02 @ position: 1
27-Jan-2022 10:47:35 - DEBUG   :: mylar.parseit.477 : MAIN : checking date : 2014
27-Jan-2022 10:47:35 - DEBUG   :: mylar.parseit.485 : MAIN : date: 2014
27-Jan-2022 10:47:35 - DEBUG   :: mylar.parseit.839 : MAIN : datecheck: [{'date': '2014', 'position': 9, 'mod_position': 35}]
27-Jan-2022 10:47:35 - DEBUG   :: mylar.parseit.845 : MAIN : sctd: 2022
27-Jan-2022 10:47:35 - DEBUG   :: mylar.parseit.853 : MAIN : year verified as : None
27-Jan-2022 10:47:35 - DEBUG   :: mylar.parseit.861 : MAIN : year verified as: 2014
27-Jan-2022 10:47:35 - DEBUG   :: mylar.parseit.893 : MAIN : highest_series_position: 9
27-Jan-2022 10:47:35 - DEBUG   :: mylar.parseit.991 : MAIN : issue_position: 10
27-Jan-2022 10:47:35 - DEBUG   :: mylar.parseit.1014 : MAIN : Possible UNKNOWN TPB/GN/HC {One-Shot} detected. Volume assumption is number: {'position': 1, 'volume': '02'}
27-Jan-2022 10:47:35 - DEBUG   :: mylar.parseit.1037 : MAIN : Volume detected as : v02
27-Jan-2022 10:47:35 - DEBUG   :: mylar.parseit.1139 : MAIN : ALT-SERIES NAME [ISSUE TITLE]: Zero v02 [None]
27-Jan-2022 10:47:35 - DEBUG   :: mylar.parseit.1154 : MAIN : sf_highest_series_pos: ['Zero']
27-Jan-2022 10:47:35 - DEBUG   :: mylar.parseit.1155 : MAIN : yearposition: 9
27-Jan-2022 10:47:35 - DEBUG   :: mylar.parseit.1158 : MAIN : split_file array size: 10
27-Jan-2022 10:47:35 - ERROR   :: mylar.excepthook.315 : MAIN : Uncaught exception: Traceback (most recent call last):
  File "/app/mylar3/Mylar.py", line 449, in <module>
    main()
  File "/app/mylar3/Mylar.py", line 315, in main
    restart_method = ur.update_db()
  File "/app/mylar3/mylar/maintenance.py", line 507, in update_db
    filelist = flc.listFiles()
  File "/app/mylar3/mylar/filechecker.py", line 117, in listFiles
    runresults = self.parseit(self.dir, self.file)
  File "/app/mylar3/mylar/filechecker.py", line 1159, in parseit
    logger.fdebug('split_file[yearposition+1]: %s' % split_file[yearposition+1])
IndexError: list index out of range
```

**Environment (please complete the following information):**
 - OS: Running in a Debian based Docker on ArchLinux
 - Branch / commit: Dev

**Comment by evilhero** [comment] 2022-01-27 19:12
I think you need to make sure you're running the latest version of whichever branch you're running. 

That logging line doesn't exist in any current build, and I couldn't find any reference to it in the past 6 months ( I only went back 6 months in the history ). 

It is just that tho - a logging line that's causing the error. It was added at some point(?) I guess and quickly removed thereafter, as it's not needed as the actual logic handles all of the calcs and that line was just to reference what was being printed out. It's been removed, so you probably need to just update your docker image.

**Comment by ajw107** [comment] 2022-01-27 20:38
Hi,
Thank you for your quick reply. Apologies for not explaining myself properly, as I mentioned in my initial post, I added extra debug logging just to see what was going on (i.e. show all variables concerned in the if statement on line 1170, and find out which one is causing the error).  Here is that extra debugging code (not meant to be used as a fix, just for you to see what was happening), I've included a line of your code at the start, so you can see it's location, which is at line 1154 and prefixed my extra logging lines with an '+':
```
        logger.fdebug('sf_highest_series_pos: %s' % split_file[:highest_series_pos])
+        logger.fdebug('yearposition: %s' % yearposition)
+        if yearposition is not None:
+            logger.fdebug('split_file array size: %s' % len(split_file))
+            logger.fdebug('split_file[yearposition+1]: %s' % split_file[yearposition+1])
+            logger.fdebug('re.sub([\.\s], , split_file[yearposition+1]): %s' % re.sub('[\.\s]', '', split_file[yearposition+1]))
+            logger.fdebug('re.sub([\.\s], , split_file[yearposition+1]).strip(): %s' % re.sub('[\.\s]', '', split_file[yearposition+1]).strip(>
+            logger.fdebug('split_file[yearposition+1].lower(): %s' % split_file[yearposition+1].lower())
+            logger.fdebug('split_file[yearposition:highest_series_pos]: %s' % split_file[yearposition:highest_series_pos])
```
They are not in the original code, but left in so you can see more about what is going on.

The error in these logs therefore occurs at the time the variable is output to the logs, rather than in the multi-part if statement, allowing you to see which part of the if statement is of concern.  In every case it fails when trying to increase the index of the `split_file array` +1 above the `yearposition`.  From the logs, you can see the contents of split_files has nothing after the year, to incrementing by one is not possible here.

Using this information I added the extra guard to line 1170, and after a few more test runs, removed my extra debug lines above and everything seems to work.  That is the DB is allowed to go through the upgrade process until completion.  The git commit I used (with my additions on top) was: 9ac720d76ac93185692a9b6d60427f91efe90062

Again, sorry for the confusion, and hope this clears things up.

**Comment by ajw107** [comment] 2022-01-28 20:59
Here is an example debug log using untouched code (i.e. without my extra logging statements):
```
28-Jan-2022 20:25:57 - DEBUG   :: mylar.parseit.370 : MAIN : Improperly formatted filename - there is no seperation using appropriate
characters between wording.
28-Jan-2022 20:25:57 - DEBUG   :: mylar.parseit.447 : MAIN : NEWLY SPLIT REORGD: ['1936']
28-Jan-2022 20:25:57 - DEBUG   :: mylar.parseit.451 : MAIN : Improperly formatted filename - there is no seperation using appropriate
characters between wording.
28-Jan-2022 20:25:57 - DEBUG   :: mylar.parseit.477 : MAIN : checking date : 1936
28-Jan-2022 20:25:57 - DEBUG   :: mylar.parseit.485 : MAIN : date: 1936
28-Jan-2022 20:25:57 - DEBUG   :: mylar.parseit.839 : MAIN : datecheck: [{'date': '1936', 'position': 0, 'mod_position': 0}]
28-Jan-2022 20:25:57 - DEBUG   :: mylar.parseit.845 : MAIN : sctd: 2022
28-Jan-2022 20:25:57 - DEBUG   :: mylar.parseit.853 : MAIN : year verified as : None
28-Jan-2022 20:25:57 - DEBUG   :: mylar.parseit.861 : MAIN : year verified as: 1936
28-Jan-2022 20:25:57 - DEBUG   :: mylar.parseit.893 : MAIN : highest_series_position: 0
28-Jan-2022 20:25:57 - DEBUG   :: mylar.parseit.991 : MAIN : issue_position: 1
28-Jan-2022 20:25:57 - DEBUG   :: mylar.parseit.1017 : MAIN : No issue number present in filename.
28-Jan-2022 20:25:57 - DEBUG   :: mylar.parseit.1154 : MAIN : sf_highest_series_pos: []
28-Jan-2022 20:25:57 - ERROR   :: mylar.excepthook.315 : MAIN : Uncaught exception: Traceback (most recent call last):
  File "/app/mylar3/Mylar.py", line 449, in <module>
    main()
  File "/app/mylar3/Mylar.py", line 315, in main
    restart_method = ur.update_db()
  File "/app/mylar3/mylar/maintenance.py", line 507, in update_db
    filelist = flc.listFiles()
  File "/app/mylar3/mylar/filechecker.py", line 117, in listFiles
    runresults = self.parseit(self.dir, self.file)
  File "/app/mylar3/mylar/filechecker.py", line 1170, in parseit
    if re.sub('[\.\s]', '', split_file[yearposition+1]).strip().lower() == 'ad' or all([split_file[yearposition+1].lower() == 'a' and
split_file[yearposition+2].lower() == 'd']):
IndexError: list index out of range
```
Note it's just giving the title as `1936` here for some reason, with the extra logging I put in we get:
```
28-Jan-2022 20:49:25 - DEBUG   :: mylar.parseit.447 : MAIN : NEWLY SPLIT REORGD: ['DC', 'Comics', 'Complete', 'Collection', '-', '1935']
28-Jan-2022 20:49:25 - DEBUG   :: mylar.parseit.477 : MAIN : checking date : 1935
28-Jan-2022 20:49:25 - DEBUG   :: mylar.parseit.485 : MAIN : date: 1935
28-Jan-2022 20:49:25 - DEBUG   :: mylar.parseit.839 : MAIN : datecheck: [{'date': '1935', 'position': 5, 'mod_position': 32}]
28-Jan-2022 20:49:25 - DEBUG   :: mylar.parseit.845 : MAIN : sctd: 2022
28-Jan-2022 20:49:25 - DEBUG   :: mylar.parseit.853 : MAIN : year verified as : None
28-Jan-2022 20:49:25 - DEBUG   :: mylar.parseit.861 : MAIN : year verified as: 1935
28-Jan-2022 20:49:25 - DEBUG   :: mylar.parseit.893 : MAIN : highest_series_position: 5
28-Jan-2022 20:49:25 - DEBUG   :: mylar.parseit.913 : MAIN : possible_issuenumbers: [{'number': '1935', 'position': 5, 'mod_position': 32,
'validcountchk': False}]
28-Jan-2022 20:49:25 - DEBUG   :: mylar.parseit.919 : MAIN : hyphen located at position: 30
28-Jan-2022 20:49:25 - DEBUG   :: mylar.parseit.921 : MAIN : yearposition: 5
28-Jan-2022 20:49:25 - DEBUG   :: mylar.parseit.930 : MAIN : Numeric detected as the last digit after a hyphen. Typically this is the issue
number.
28-Jan-2022 20:49:25 - DEBUG   :: mylar.parseit.962 : MAIN : issue number :1935
28-Jan-2022 20:49:25 - DEBUG   :: mylar.parseit.991 : MAIN : issue_position: 5
28-Jan-2022 20:49:25 - DEBUG   :: mylar.parseit.1019 : MAIN : issue verified as : 1935
28-Jan-2022 20:49:25 - DEBUG   :: mylar.parseit.1139 : MAIN : ALT-SERIES NAME [ISSUE TITLE]: DC Comics Complete Collection [None]
28-Jan-2022 20:49:25 - DEBUG   :: mylar.parseit.1154 : MAIN : sf_highest_series_pos: ['DC', 'Comics', 'Complete', 'Collection', '-']
28-Jan-2022 20:49:25 - DEBUG   :: mylar.parseit.1155 : MAIN : yearposition: 5
28-Jan-2022 20:49:25 - DEBUG   :: mylar.parseit.1157 : MAIN : split_file array size: 6
28-Jan-2022 20:49:25 - ERROR   :: mylar.excepthook.315 : MAIN : Uncaught exception: Traceback (most recent call last):
  File "/app/mylar3/Mylar.py", line 449, in <module>
    main()
  File "/app/mylar3/Mylar.py", line 315, in main
    restart_method = ur.update_db()
  File "/app/mylar3/mylar/maintenance.py", line 507, in update_db
    filelist = flc.listFiles()
  File "/app/mylar3/mylar/filechecker.py", line 117, in listFiles
    runresults = self.parseit(self.dir, self.file)
  File "/app/mylar3/mylar/filechecker.py", line 1158, in parseit
    logger.fdebug('split_file[yearposition+1]: %s' % split_file[yearposition+1])
IndexError: list index out of range
```
which seems to suggest that it's actually `1935` year (just noticed that, could the year have been decrememented somewhere, is it somehow a completely different DB record it has stopped at, agh) and the title as `DC Comics Complete Collection [None]`

**Comment by evilhero** [comment] 2022-01-28 21:13
Yeah see the problem is the fileparser is built to check filenames that well exist as filenames. The updater uses the filechecker module to parse out filenames from the rss feed database - which, obviously can be all over the board depending on which providers you use within Mylar.

I think we can get around all of this by adding in a well-placed try / except catch and have it return something that doesn't break but continues trucking.

Thanks for all the detailed info - I'm looking more into this right now

**Comment by evilhero** [comment] 2022-01-28 22:28
So in testing this I added in some deletion routines in with the checking since it's going thru each entry in the rss table and there are probably alot of items that would never parse anyways.

So using your ``1936`` example (I just added an entry with the name being just 1936):
```28-Jan-2022 17:20:29 - DEBUG   :: mylar.parseit.370 : MAIN : Improperly formatted filename - there is no seperation using appropriate characters between wording.
28-Jan-2022 17:20:29 - DEBUG   :: mylar.parseit.373 : MAIN : NEW split_file3: ['1936']
28-Jan-2022 17:20:29 - DEBUG   :: mylar.parseit.447 : MAIN : NEWLY SPLIT REORGD: ['1936']
28-Jan-2022 17:20:29 - DEBUG   :: mylar.parseit.451 : MAIN : Improperly formatted filename - there is no seperation using appropriate characters between wording.
28-Jan-2022 17:20:29 - DEBUG   :: mylar.parseit.477 : MAIN : checking date : 1936
28-Jan-2022 17:20:29 - DEBUG   :: mylar.parseit.485 : MAIN : date: 1936
28-Jan-2022 17:20:29 - DEBUG   :: mylar.parseit.839 : MAIN : datecheck: [{'date': '1936', 'position': 0, 'mod_position': 0}]
28-Jan-2022 17:20:29 - DEBUG   :: mylar.parseit.845 : MAIN : sctd: 2022
28-Jan-2022 17:20:29 - DEBUG   :: mylar.parseit.853 : MAIN : year verified as : None
28-Jan-2022 17:20:29 - DEBUG   :: mylar.parseit.861 : MAIN : year verified as: 1936
28-Jan-2022 17:20:29 - DEBUG   :: mylar.parseit.893 : MAIN : highest_series_position: 0
28-Jan-2022 17:20:29 - DEBUG   :: mylar.parseit.991 : MAIN : issue_position: 1
28-Jan-2022 17:20:29 - DEBUG   :: mylar.parseit.1017 : MAIN : No issue number present in filename.
28-Jan-2022 17:20:29 - DEBUG   :: mylar.parseit.1154 : MAIN : sf_highest_series_pos: []
28-Jan-2022 17:20:29 - INFO    :: mylar.update_db.518 : MAIN : [MAINTENANCE-MODE][DB-CONVERSION][JUNK-NAME] 1936
```
No error, as the try/except stops it from doing that and it gets thrown into the 'to be deleted' variable (which deletes from the rssdb table only, nothing else).

And then your DC Collection example:
```
28-Jan-2022 17:20:29 - DEBUG   :: mylar.parseit.1019 : MAIN : issue verified as : 1935
28-Jan-2022 17:20:29 - DEBUG   :: mylar.parseit.1139 : MAIN : ALT-SERIES NAME [ISSUE TITLE]: DC Comics Complete Collection [None]
28-Jan-2022 17:20:29 - DEBUG   :: mylar.parseit.1154 : MAIN : sf_highest_series_pos: ['DC', 'Comics', 'Complete', 'Collection', '-']
28-Jan-2022 17:20:29 - DEBUG   :: mylar.parseit.1206 : MAIN : series title possibly: DC Comics Complete Collection
28-Jan-2022 17:20:29 - DEBUG   :: mylar.parseit.1219 : MAIN : Alternate series / issue title: DC Comics Complete Collection [None]
```
Note that the ``[None]`` is what the issue title is or was parsed as - the actual name of the title does not include that (again for display purposes in the log only it was added).

So yeah, think this works pretty well now - it will also delete any rss entries that are invalid, don't parse or contain extensions that aren't comic related. I'll be pushing this up to python3-dev in a little bit and you can test it then and give some feedback if you'd like.

**Comment by barbequesauce** [comment] 2022-03-25 01:34
@ajw107 are we good to close?

**Comment by evilhero** [comment] 2022-03-30 20:08
Assuming fixed - so closing.

**Closed by evilhero** 2022-03-30 20:08 UTC
Labels: bug
