### ISSUE TITLE
Mylar3 won't start

### ISSUE THREAD

**Issue by shredness** [mylar3/mylar3#1106] opened 2022-03-16 12:14 UTC
using linuxserver/mylar:latest docker. after recent pull, mylar3 starts but loops the following error:

16-Mar-2022 12:13:29 - INFO :: mylar.configure.1137 : MainThread : Ignored Publishers: []
16-Mar-2022 12:13:29 - INFO :: mylar.configure.1160 : MainThread : [MASS_PUBLISHERS] Auto-add for weekly publishers set to: []
16-Mar-2022 12:13:29 - INFO :: mylar.configure.1172 : MainThread : [PROBLEM_DATES] Problem dates loaded: ['2021-07-14 04:00:34']
16-Mar-2022 12:13:29 - INFO :: mylar.configure.1186 : MainThread : [COMICTAGGER] Version detected: 1.3.4
16-Mar-2022 12:13:29 - INFO :: mylar.configure.1265 : MainThread : Setting DDL Location set to : /config/mylar/cache
16-Mar-2022 12:13:29 - INFO :: mylar.initialize.222 : MainThread : Checking to see if the database has all tables....
16-Mar-2022 12:13:29 - INFO :: mylar.dbcheck.1575 : MainThread : Ensuring DB integrity - Removing all Erroneous Comics (ie. named None)
16-Mar-2022 12:13:29 - INFO :: mylar.dbcheck.1585 : MainThread : Correcting Null entries that make the main page break on startup.
16-Mar-2022 12:13:29 - INFO :: mylar.dbcheck.1596 : MainThread : [<class 'int'>]oldconfig_version: 12
log language set to en_US
Initializing startup sequence....
16-Mar-2022 12:13:29 - ERROR :: mylar.excepthook.315 : MainThread : Uncaught exception: Traceback (most recent call last):
  File "/app/mylar3/Mylar.py", line 449, in <module>
    main()
  File "/app/mylar3/Mylar.py", line 248, in main
    mylar.initialize(mylar.CONFIG_FILE)
  File "/app/mylar3/mylar/__init__.py", line 228, in initialize
    cc.provider_sequence()
  File "/app/mylar3/mylar/config.py", line 1635, in provider_sequence
    self.write_out_provider_searches()
  File "/app/mylar3/mylar/config.py", line 1748, in write_out_provider_searches
    writeout = myDB.upsert("provider_searches", vals, ctrls)
  File "/app/mylar3/mylar/db.py", line 173, in upsert
    self.action(query, list(valueDict.values()) + list(keyDict.values()))
  File "/app/mylar3/mylar/db.py", line 130, in action
    sqlResult = self.connection.execute(query, args)
sqlite3.IntegrityError: UNIQUE constraint failed: provider_searches.id

**Comment by shredness** [comment] 2022-03-16 13:45
I'm able to reproduce the issue. the clue is in the error "provider_searches"
Editing the config.ini file directly, and removing any reference to any NZB provider, allows the app to run.
In the GUI, under Search Providers, if I add the preconfigured NZBsu entry, the config cannot be saved through the GUI. The app fails to run after restart. If I manually add NZB.su as a Newznab entry, again the application fails.
I can add other entries, jsut not NZBsu. I think this is where the problem is.

**Comment by evilhero** [comment] 2022-03-16 14:07
This is isolated to your setup - your db file has entries in that particular table that are invalid and causing a problem. nzbsu works as intended as a provider otherwise. 

What I would need to see is your db file - either by itself, or in a carepackage.

**Comment by shredness** [comment] 2022-03-16 14:19
[carepackage.zip](https://github.com/mylar3/mylar3/files/8262936/carepackage.zip)
It could be, I have no doubt. Carepackage attached. Thanks!

**Comment by evilhero** [comment] 2022-03-25 22:53
With Mylar shutdown, set the config.ini setting ``clear_provider_searches = True``, save it and then start up Mylar. You should be good thereafter.

Note that you currently cannot have nzb.su indicated as a newznab provider - you need to use the nzb.su predefined option within Mylar (at the moment at least).  

In the next few commit (or at some point soon, maybe not the immediate next few) the nzb.su and dognzb predefined options will be transferred to the newznab section as they shouldn't need any special accommodation by Mylar.

**Comment by jwm-evans** [comment] 2022-03-27 10:52
I had this issue as well. I tried adding that setting to my config.ini but it didn't help. However, I saw a similar one: `clear_provider_table`. Setting that to True did resolve the issue.

**Comment by evilhero** [comment] 2022-03-30 20:51
Options are available now in both master & python3-dev branches to help fix this issue.

See [here](https://github.com/mylar3/mylar3/wiki/Common-Errors---Problems#on-startup-i-get-an-error-about) for further information (same information as provided in last 2 comments here)

Closing as resolved.

**Closed by evilhero** 2022-03-30 20:51 UTC
Labels: pending testing
