### ISSUE TITLE
Folder Monitoring Job Not Running / Manual Import 1 Issue per Click

### ISSUE THREAD

**Issue by undaunt** [mylar3/mylar3#608] opened 2021-01-15 23:00 UTC
**Describe the bug**
I've set Enable Folder Monitoring to true so as to import existing files from my old setup. I also intend on using this folder to eventually import finished torrent downloads. Currently, the automated job appears not to be running at all, though I cannot detect anything from the logs even with debug. To be fair, I'm not sure precisely what I'm looking for.

Additionally, when I manually trigger a manual post-process, it will only grab one file at a time. If I press the button again 5-10 seconds later, it will import another file successfully. However, it only ever does one at a time. (All files were properly manually updated to include [__COMICID__] in advance.) I proceeded to do this 42 times to import my existing comic collection after trying to test the automated import for an hour or so.

**CarePackage**
[carepackage.zip](https://github.com/mylar3/mylar3/files/5823293/carepackage.zip)

**Environment (please complete the following information):**
 - OS: LSIO Docker on Ubuntu 20.04
 - Branch / commit: master 0.4.9.3 (build ac29fdbac4acd054523290a5564d24b3720dd2f6)

**Additional information**
As there is no completed download handling for torrents, which is my exclusive download source, it is my understanding that post processing of folder monitoring (and copying the files so I may seed, and enable metadata tagging) is the best course of action. Please let me know if this is not correct or if I can improve my workflow here.

Thanks very much!

**Comment by evilhero** [comment] 2021-01-17 19:24
Looking at the log, it looks like there's a glitch in the ```[___ISSUEID___]``` aspect that you added to every filename that you're trying to post-process manually. So it does one issue, and then it stops (which is the glitch part) the post-processing completely (and because the issueid-files get sorted by priority first, it just stops everything). 

So that needs to get addressed. You'll have to either wait for the patch to hit, or just remove the ```[___ISSUEID___]``` from each filename and possibly rename the filename so that it conforms to a naming convention that's parsable (typically just ```Series Issue (Year)``` is an easy bet, ```Series #Issue (Year)``` even more so since you're denoting the issue number specificaly). Note that if you have renaming enabled, Mylar will rename the file during the post-processing of it so however you name it initially won't be the final end result (which might be desirable).

You've obviously come to the conclusion that the files that you were trying to post-process (prior to adding in the identification part), weren't able to be detected due to the naming convention - which is correct based on the names I saw in the log.

As far as the folder monitor not working - I don't see any mention of it in the logs as being updated even. Normally when you toggle the Folder Monitor option in the configuration and save the settings, you'll get a blurb in the log about the monitor thread starting up, which is not present from what I can see. Is it possible that added the value to the ini when Mylar was still running ?  Have you restarted Mylar subsequently since enabling the option?

**Comment by undaunt** [comment] 2021-01-18 00:37
@evilhero Hey, you are exactly correct regarding the filename piece. I had some Humble Bundle Pathfinder comics and those were name with the rather unusual names so I added the Comic Vine ID into the path for (what I thought would be) easiest matching/name recognition.

I can definitely wait for a patch to match any outliers as the majority of my comics are not named as such. I loaded some others into a manual post process location and 40+ of them processed without issue.

I do in fact have renaming enabled, so the differences between my download location and the comic series location are detectable but minor (and intended) changes. (Example: Rick and Morty 001 (2015).cbr -> Rick and Morty 1 (2015).cbz.

I'm doing copying instead of hardlink so I can continue to seed but also have the metadata embedded - is that the best course? IE: Do writing the metadata tagging, comicrack, and comicbooklover tags get written into the actual .cbr/.cbz files? If not, I should probably change to just hardlink to save on disk space. I also noticed just now that Mylar appears to be converting .cbr source files into .cbz target files. Is that due to embedding the metadata?

Regarding folder monitor, yes I've disabled and re-enabled the setting to test. I didn't manually edit the .ini file while Mylar was on. Typically I would either change any setting via UI, or stop the docker container, remove volumes, then update, then restart docker. I have in fact restarted Mylar at least twice since setting the monitoring setting but can definitely attempt to again.

Thanks very much.

**Comment by undaunt** [comment] 2021-01-18 20:59
@evilhero I turned folder monitoring off, manually shut down the docker, removed volumes from docker, then manually turned monitoring on via the .ini file directly. It now appears to be working correctly. It imported 16 volumes of the Walking Dead but I'll likely need to clean up the file names for the rest so let's assume that portion is resolved.

Is there a way to expose via the logs what part of a given filename would kill any manual or folder monitoring type scan to help let me or other users know which ones are the troublesome files on an ongoing, self-service basis?

I'll also wait for the patch you referred to.

Thanks!

**Comment by evilhero** [comment] 2021-01-19 15:49
If you enable debug logging (either start it with the **-v** switch, or set your log_level in the config.ini to 2) it'll start Mylar up with verbose logging enabled. You can also enable it via the **History tab** / **View Logs** / **Toggle Verbose Logging On**, which sets the logging to verbose, but only logs in that mode from that point forward. Note that if you''re using docker, there was an issue with the command switch being set to -q on startup (which then over-rides any ini value and sets the logging to WARNING levels) - although I think that may have been fixed in one of the recent updates (this was for the linuxserver docker).

With debug logging enabled, you'll be able see in the logs the files that are not able to be parsed. I believe the files that have failed to parse are logged in a grouping with the logging line of **FAILED FILES:** Note that it's very possbile for a file to parse properly, but fail to match to the given series for a variety of reasons (which won't be denoted in the failed files aspect probably).

There is no function in the GUI as of yet to see the failed filenames, albeit there should be something to denote the failure(s) in the GUI somewhere - might have to take a look more into that when time permits.

As far as your copying/hardlinking question - yes, if you're wanting to seed the torrents but attach metadata, you're only option is to use copy. That will allow you to 'tag' the copied files with metadata ( depending on your choices, it will either store it in the comicinfo.xml (CR) or the zip header (CBL), but both within the zip file), while retaining your original files -albeit at the cost of some extra storage space. And yes, Mylar uses a built-in, modified version of ComicTagger to tag the files - since cbr's with metadata aren't really an accepted standard (there's alot of problems with using metadata and that format with readers, plus the whole proprietary aspect of the rar program).  So it converts cbrs --> cbz and then attaches the relevant metadata to the zip file. 

You can view the metadata of files within Mylar by clicking on the **'i'** icon on the series detail page. Depending on what format the issue is the colour of the 'i' will be different:
- blue: the file is a cbz file and probably contains metadata. If it does, it will display it, otherwise it will be blank with a warning.
- orange: the file is a cbr file and does not contain metadata (it will dispaly the main image of the file, with a warning).
- grey: there is no file present on the system, so it will retrieve some basic metadata directly from CV and display it.

Right now you can only view the metadata, but eventually an editor will be available that will allow you to edit the relevant metadata right in the GUI.

Hope that helps!

**Comment by undaunt** [comment] 2021-01-19 16:45
Thanks for the tip about the log level setting within the .ini. I had previously been looking through debug post launch for why the folder monitoring hadn't been working before - though that's all set now. I'll dig further into the specifics of my situation re: the matching.

I'll keep everything on copy then, thanks for the insight with regard to the metadata types and standards - exceedingly helpful. Should we keep this issue open for any potential fix on the original type of file I had that broke the scanner loop?

Thanks again.

**Comment by evilhero** [comment] 2021-01-19 18:47
The fix is in PR #611 now.

We can keep this open until the merge to master happens if you'd like to confirm that everything works as intended at that point. It might be a few days until that happens depending on time however.

**Closed** 2021-03-12 18:33 UTC
Labels: bug
