### ISSUE TITLE
Feedparser 6.0.0 breaks mylar

### ISSUE THREAD

**Issue by ajslater** [mylar3/mylar3#452] opened 2020-09-13 20:17 UTC
https://github.com/mylar3/mylar3/blob/de480e50a6b32066ad8f7d3568aaf1aef06185af/requirements.txt#L13

```
mylar    | AttributeError: module 'feedparser' has no attribute '_FeedParserMixin'
```

The simplest workaround for the moment would be to require feedparser==^5.2.1

But it doesn't look like upgrading mylar will take to much work either. I'll look into it.

**Comment by evilhero** [comment] 2020-09-13 20:27
duplicate of #451

**Closed by evilhero** 2020-09-13 20:27 UTC
