### ISSUE TITLE
story arcs and annual integration

### ISSUE THREAD

**Issue by HypKin** [mylar3/mylar3#346] opened 2020-06-14 11:29 UTC
**Describe the bug**
if a story arc includes annuals, that said annuals are shown as missing even tough they are already in the library of the main series. 

**CarePackage**
I'm getting a 500 error when trying to create a care package...

**Environment (please complete the following information):**
 - OS: windows 10 
Mylar Version: master 
-- git (build e29114901810346e52486c8681c6b154639bcf86)

**Additional information**
https://github.com/mylar3/mylar3/issues/243 I think was talking about the same problem. 

now i did the following:

1. i have all existing boom studios power rangers comics in the library. that includes the main series

https://comicvine.gamespot.com/mighty-morphin-power-rangers/4050-87332/

I also optioned for integrating the annuals in the main series, there are currently 4 annuals for this comic

![image](https://user-images.githubusercontent.com/15702664/84591961-ba9ac080-ae42-11ea-9110-f5288f2667e4.png)

ok, so far so good.

today I added "shattered grid" via the search function in the story arc management. this includes the 2018 annual. but it says that this comic is missing. 

![image](https://user-images.githubusercontent.com/15702664/84592037-e1f18d80-ae42-11ea-9b1b-1798aefd5803.png)

2 questions: the annual in the story arc management and the series overview have different titels/names - could this be the reason?

and second: since i seem to not be able to create a care package, what actions should i perform to give you a debug log thats helping? turning on debugging and then searching for something? or readding this story arc?

**Comment by barbequesauce** [comment] 2020-06-15 01:28
Hi Hypkin -

If you can post a debug log it would help tremendously.

Also - I'd like to see the 500 error if you wouldnt mind?

**Comment by HypKin** [comment] 2020-06-20 20:43
for the 500 error I'm getting this

`500 Internal Server Error
The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\cherrypy\_cprequest.py", line 638, in respond
    self._do_respond(path_info)
  File "C:\Python37\lib\site-packages\cherrypy\_cprequest.py", line 697, in _do_respond
    response.body = self.handler()
  File "C:\Python37\lib\site-packages\cherrypy\lib\encoding.py", line 219, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "C:\Python37\lib\site-packages\cherrypy\_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "D:\mylar3\mylar\webserve.py", line 5754, in carepackage
    cp = carePackage()
  File "D:\mylar3\mylar\carepackage.py", line 84, in __init__
    self.environment()
  File "D:\mylar3\mylar\carepackage.py", line 99, in environment
    text=True)
  File "C:\Python37\lib\subprocess.py", line 474, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "C:\Python37\lib\subprocess.py", line 939, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "C:\Python37\lib\subprocess.py", line 1288, in _communicate
    stdout = stdout[0]
IndexError: list index out of range
Powered by CherryPy 18.6.0`


for the logs i did the following:
1. deleted all logs
2. started mylar with -v 
3. deleted the stroy arc "shattered grid"
4. readded the "shattered grid" story arc
5. tried again to create a care package.
6. shut down mylar

[mylar.log](https://github.com/mylar3/mylar3/files/4808528/mylar.log)


hope this is what you had in mind @barbequesauce

**Comment by barbequesauce** [comment] 2020-06-21 01:53
so the carepackage issue is trying to run `uname -a` on a windows box. Not sure why the switch doesnt detect the OS as Windows...

What does `python3 -c "import platform; print(platform.system())"` output?

**Comment by HypKin** [comment] 2020-06-21 09:58
Output is "Windows"

![image](https://user-images.githubusercontent.com/15702664/85221727-8d0bc500-b3b6-11ea-83fd-0f7b6586aad7.png)

**Comment by barbequesauce** [comment] 2020-06-21 15:25
Just pushed a tweak for the carepackage 500 error, if you can give that another shot when you have time please...

As for the original issue - I believe the different naming is what's throwing it. Mylar has no way of knowing the two names should be covered by the one file.

**Comment by HypKin** [comment] 2020-06-21 19:41
as mentionend in #356 I'm still getting an 500 error. 

coming back to the initial error I don't really understand your feedback about the naming.

![image](https://user-images.githubusercontent.com/15702664/85233464-bb18f580-b406-11ea-8967-fce1c3b2caea.png)


ok the Name in the Story Arc list is

Mighty Morphin Power Rangers 2018 Annual (2018)

but in this list "Name" is not filled by the same data as it is in the series overview. "name" in this context is the series name, as you can see with the other issues in the screenshot. 

the "name" fild is filled with meta data in the series overview like this

![image](https://user-images.githubusercontent.com/15702664/85233495-1ba83280-b407-11ea-852d-c0b4404596ad.png)


sooo, the name that we are looking for is the "series name" and since I integrated the annuals that means that name is displayed in the annual header:

![image](https://user-images.githubusercontent.com/15702664/85233617-f8ca4e00-b407-11ea-92ca-71d334d7626a.png)


so I do think that mylar should know, that this is the same issue

**Comment by evilhero** [comment] 2020-06-21 20:52
This is the same as #243, which was an outstanding issue. I can confirm that it's a problem with the linking of annuals and series to the correct id's, as I looked into this again just last week. 

It's far more deeper problem than just the linking however, as it also affects items that are part of the pull in some instances. 

I'm also about half way thru fixing this, so atm it's still an outstanding issue.

**Comment by HypKin** [comment] 2020-06-22 06:50
ah, thank you for clarifying, I thought #243 was dead since the author didn't answer anymore ;)

**Comment by evilhero** [comment] 2022-03-30 17:46
@HypKin I know this has been forever, but I'm pretty sure this has been addressed for awhile now - but just clarifying that it's working as intended. I'm going to close this assuming such, but if it's still an issue please open a new issue in regards to the problem so that it gets proper attention.

**Closed by evilhero** 2022-03-30 17:46 UTC
Labels: bug, StoryArc rewrite
