### ISSUE TITLE
After updates, Mylar won’t restart and searching for new comics results in 500 error.

### ISSUE THREAD

**Issue by AtariBaby** [mylar3/mylar3#1105] opened 2022-03-16 04:52 UTC
**Describe the bug**
1. Starting with the last two updates, after installing the update, Mylar doesn’t restart. “Server stopped responding”. I have to double-click mylar.pyw to start it now. Similarly, if I click the link for “Restart”, it doesn’t.

2. _(UPDATE: evilhero says a new master update will fix this problem, coming within hours. Read this thread for more details):_ If I search for a new comic, I get: 

500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\site-packages\cherrypy\_cprequest.py", line 638, in respond
    self._do_respond(path_info)
  File "C:\Program Files\Python37\lib\site-packages\cherrypy\_cprequest.py", line 697, in _do_respond
    response.body = self.handler()
  File "C:\Program Files\Python37\lib\site-packages\cherrypy\lib\encoding.py", line 223, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "C:\Program Files\Python37\lib\site-packages\cherrypy\_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "C:\mylar3\mylar\webserve.py", line 997, in searchit
    for x in searchresults:
TypeError: 'bool' object is not iterable
Powered by [CherryPy 18.6.1](http://www.cherrypy.org/)

**CarePackage**
[carepackage 12.zip](https://github.com/mylar3/mylar3/files/8258979/carepackage.12.zip)
On the config page, there is a button labelled "CarePackage". Pressing this button will download a zip file containing a redacted copy of your config, your database, a summary of your operating environment, and your logs. Upload that file here.

If you're uncomfortable with pasting your CarePackage, include a DEBUG log containing the error from disk. 

Do not paste from the GUI log.
Do not just paste a traceback/error.

**Environment (please complete the following information):**
 - OS:  Windows10
 - Branch / commit: [1ac9c18736170bf8b2d585fc67e467ed02da0d7d]

**Additional information**
This is all new behavior

**Comment by BRTPOB** [comment] 2022-03-16 08:25
This is due to ComicVine. It seems someone/some people were hammering the API and so now the User Agent is blocked. The latest dev build has a config option to replace your User Agent to a custom one.

**Comment by jakem742** [comment] 2022-03-16 10:30
Glad it's not just me! I imagine this is the kind of thing that is likely to resolve itself within ~24hrs and you can just wait it out...? Are there any guides or posts I can use to help with replacing the user agent in case I get desperate?

**Comment by BRTPOB** [comment] 2022-03-16 10:40
I don't think waiting it out will be super helpful, unfortunately. If you've gotten the new version, I can work with evilhero to put together a guide.

**Comment by jakem742** [comment] 2022-03-16 11:08
I've just pulled the latest docker image for v0.6.5.1 and am having this issue. A guide would be amazing! Alternatively, I'm happy to muddle my way through it if you can point out any existing discussion where people got a custom user agent working?

**Comment by evilhero** [comment] 2022-03-16 14:14
When it merges up into master you don't need to do anything. The UA agent defaults to a semi-current one if nothing is specified, so all you literally have to do is update Mylar for things to work.

If it happens again, or for whatever reason you want to change it, there's a field called ``cv_user_agent`` in the config.ini in which you can manually add in a different one. To find different User-Agents just do a simple google search for ``user-agent strings`` and you should be able to find a wide variety.

But again, the default UA that's used now if nothing is specified by the user, works fine.

**Comment by AtariBaby** [comment] 2022-03-16 14:38
> But again, the default UA that's used now if nothing is specified by the user, works fine.

Hi evilhero, mine is still giving me the 500 server error. And how do I get it to automatically restart again now?

**Comment by evilhero** [comment] 2022-03-16 14:42
Nothing has merged into master yet. That will be in about an hr or so hopefully. Until then you'll keep getting the 500 error.

As for the restarts, I haven't a clue atm - that sounds like a problem with the way you're starting / running mylar (nssm?)

**Comment by AtariBaby** [comment] 2022-03-16 15:11
Oh sorry, I didn’t understand! I’ll keep an eye out for the new update.

Weird, I wasn’t having this issue before, for years now.

**Comment by AtariBaby** [comment] 2022-03-16 15:16
I only have mylar.pyw in my “startup apps” folder. Not sure how it was working on its own. Is nssm the best way?

**Comment by evilhero** [comment] 2022-03-16 15:29
Make sure the Mylar.pyw in your startup folder is pointing to the new version of Mylar.py (or linking to it). If Mylar.py is updated in the repo, and you're using a different version, you'll get weird types of errors.

Check the wiki for info on NSSM

**Comment by rob88v** [comment] 2022-03-16 15:46
I can confirm I also have the 500 internal server issue with CV, I just finished setting up Mylar3 with docker and will wait for the branch to update and then try my first search.

**Comment by jakem742** [comment] 2022-03-16 22:59
This is confirmed resolved for me with the update. :) Big thanks for pushing this out so fast evilhero!

**Comment by rob88v** [comment] 2022-03-17 08:02
Working perfectly for me now as well, thank you so much!

**Comment by aleaax** [comment] 2022-03-21 21:47
Unfortunately, I still have the same issue

**Comment by aleaax** [comment] 2022-03-21 21:52
Unfortunately, I still have the same issue with whatever I search for
`ERROR :: mylar.searchit.997 : CP Server Thread-7 : Unable to retrieve results from ComicVine: 'bool' object is not iterable`
[carepackage (2).zip](https://github.com/mylar3/mylar3/files/8319432/carepackage.2.zip)

OS: macOS 12.2 
Branch: [0d508948e372ce1de1b9f228e5d9c0686ebcc3fb]

**Comment by evilhero** [comment] 2022-03-21 22:40
> Unfortunately, I still have the same issue with whatever I search for
> `ERROR :: mylar.searchit.997 : CP Server Thread-7 : Unable to retrieve results from ComicVine: 'bool' object is not iterable`
> [carepackage (2).zip](https://github.com/mylar3/mylar3/files/8319432/carepackage.2.zip)
> 
> OS: macOS 12.2 
> Branch: [0d508948e372ce1de1b9f228e5d9c0686ebcc3fb]
> 
> 

Still a problem with you getting to CV. Either your DNS hasn't updated to the new CV DNS entries, or your ISP hasn't. Either way, it's not a problem with mylar, but with your DNS entries to CV. If you're using CF for DNS, try switching to either google or opendns.

**Comment by AtariBaby** [comment] 2022-03-21 23:06
Searches now work for me also. Just confirming since some people are still having issues. My boot up  problem still exists but I can live with that

**Comment by aleaax** [comment] 2022-03-22 15:39
Thanks! Comicvine appears to be down... so yes, i'll have to be patient I guess 😄

**Closed** 2022-03-25 01:07 UTC
Labels: enhancement, metadata quality issue
